spring:
  datasource:
    url: jdbc:mysql://loansdb:3306/loansdb  
    driverClassName: com.mysql.cj.jdbc.Driver
    username: myuser
    password: mypass
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: validate