services:

  accounts:
    build:
      context: ./accounts
      dockerfile: Dockerfile
    image: debakarana/accounts:1.0
    container_name: accounts-ms
    ports:
      - "8080:8080"
    mem_limit: 512m
    cpus: 0.5
    networks:
      - bank-network

  loans:
    build:
      context: ./loans
      dockerfile: Dockerfile
    image: debakarana/loans:1.0
    container_name: loans-ms
    ports:
      - "8090:8090"
    mem_limit: 512m
    cpus: 0.5
    networks:
      - bank-network
  cards:
    build:
      context: ./cards
      dockerfile: Dockerfile
    image: debakarana/cards:1.0
    container_name: cards-ms
    ports:
      - "9000:9000"
    mem_limit: 512m
    cpus: 0.5
    networks:
      - bank-network
networks:
  bank-network:
    driver: bridge
