x-mysql-base: &mysql-base
  image: mysql:8.0
  networks:
    - bank-network
  healthcheck:
    test: ["CMD-SHELL", "mysqladmin ping -h localhost -uroot -p$MYSQL_ROOT_PASSWORD || exit 1"]
    interval: 10s
    timeout: 5s
    retries: 10
    start_period: 30s

services:

  # =========================
  # RabbitMQ (Message Broker)
  # =========================
  rabbit:
    image: rabbitmq:3.12-management          # RabbitMQ with management UI enabled
    # hostname: rabbitmq                    # Stable hostname for internal DNS
    ports:
      - "5672:5672"                       # AMQP port (used by Spring Cloud Bus)
      - "15672:15672"                     # Management UI (http://localhost:15672)
    mem_limit: 512m
    healthcheck:
      # Verifies RabbitMQ is actually accepting connections,
      # not just that the container is running
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s                       # Run health check every 10 seconds
      timeout: 50s                         # Fail if command hangs >5s
      retries: 20                         # Mark unhealthy after 10 consecutive failures
      start_period: 5s                    # Give RabbitMQ time to boot before judging

    extends:
      file: ./common-config.yml
      service: network-deploy-service


  # =========================
  # Spring Cloud Config Server
  # =========================
  configserver:
    build:
      context: ./configserver             # Build from local configserver source
      dockerfile: Dockerfile
    image: debakarana/configserver:1.0
    container_name: configserver
    ports:
      - "8071:8071"                       # Config Server port

    depends_on:
      # Config Server uses Spring Cloud Bus,
      # so RabbitMQ must be fully ready before it starts
      rabbit:
        condition: service_healthy

    healthcheck:
      # Checks Spring Boot readiness probe:
      # - JVM started
      # - Git config loaded
      # - Bus wired
      test: "curl --fail --silent localhost:8071/actuator/health/readiness | grep UP || exit 1"
      interval: 10s                       # Check every 10 seconds
      timeout: 5s                         # Fail if response >5s
      retries: 7                          # Retry before marking unhealthy
      start_period: 10s                   # Allow startup time before enforcing health

    extends:
      file: ./common-config.yml
      service: microservice-base-config

  accountsdb:
    <<: *mysql-base
    container_name: accounts-db
    env_file:
      - ./accounts/mysql.env.${SPRING_PROFILES_ACTIVE}
    volumes:
      - accounts-db-data:/var/lib/mysql

  loansdb:
    <<: *mysql-base
    container_name: loans-db
    env_file:
      - ./loans/mysql.env.${SPRING_PROFILES_ACTIVE}
    volumes:
      - loans-db-data:/var/lib/mysql

  cardsdb:
    <<: *mysql-base
    container_name: cards-db
    env_file:
      - ./cards/mysql.env.${SPRING_PROFILES_ACTIVE}
    volumes:
      - cards-db-data:/var/lib/mysql

  # =========================
  # Accounts Microservice
  # =========================
  accounts:
    build:
      context: ./accounts
      dockerfile: Dockerfile
    image: debakarana/accounts:1.0
    container_name: accounts-ms
    env_file:
      - ./accounts/app.env.${SPRING_PROFILES_ACTIVE}
    environment:
      SPRING_APPLICATION_NAME: "accounts"
    ports:
      - "8080:8080"
    depends_on:
      configserver:
        condition: service_healthy
      accountsdb:
        condition: service_healthy
    extends:
      file: ./common-config.yml
      service: microservice-configserver-config


  # =========================
  # Loans Microservice
  # =========================
  loans:
    build:
      context: ./loans
      dockerfile: Dockerfile
    image: debakarana/loans:1.0
    container_name: loans-ms
    env_file:
      - ./loans/app.env.${SPRING_PROFILES_ACTIVE}
    environment:
      SPRING_APPLICATION_NAME: "loans"
    ports:
      - "8090:8090"
    depends_on:
      configserver:
        condition: service_healthy
      loansdb:
        condition: service_healthy
    
    extends:
      file: ./common-config.yml
      service: microservice-configserver-config


  # =========================
  # Cards Microservice
  # =========================
  cards:
    build:
      context: ./cards
      dockerfile: Dockerfile
    image: debakarana/cards:1.0
    container_name: cards-ms
    env_file:
      - ./cards/app.env.${SPRING_PROFILES_ACTIVE}
    environment:
      SPRING_APPLICATION_NAME: "cards"
    ports:
      - "9000:9000"
    depends_on:
      configserver:
        condition: service_healthy
      cardsdb:
        condition: service_healthy
    extends:
      file: ./common-config.yml
      service: microservice-configserver-config


volumes:
  accounts-db-data:
  loans-db-data:
  cards-db-data:

# =========================
# Shared Docker Network
# =========================
networks:
  bank-network:
    driver: bridge                        # Enables service-name based DNS resolution
