server:
  port: 8080
spring:
  application:
    name: accounts
  sql:
    init:
      mode: always
      schema-locations: classpath:sqls/schema.sql
  config:
    import: "optional:configserver:"
management:
  endpoints:
    web:
      exposure:
        include: busrefresh  #in your microservice, we used *