server:
  port: 9000
spring:
  application:
    name: "cards"
  sql:
    init:
      mode: always
      schema-locations: classpath:sqls/schema.sql
  config:
    import: "optional:configserver:"
management:
  endpoints:
    web:
      exposure:
        include: busrefresh  #in your microservice, we used *